# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: 'Install python 3.9.13'
    command: pyenv install 3.9.13
  - name: 'Create and activate virtual environment'
    command:  python3.9 virtualenv django-env /workspace/venv

vscode:
  extensions:
    - "ms-python.python"
