# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Create and activate venv
    init: | 
      git checkout env-fix
      pyenv install 3.9.13
      pyenv virtualenv django-env
    command: |
      cd bank_project/
      pyenv activate 

ports:
  - port: 8000
    visibility: private

vscode:
  extensions:
    - "ms-python.python"
