# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Create and activate venv
    init: | 
      pyenv install 3.9.13
      python -m venv django-env /workspace/venv --upgrade-deps
    command: source /workspace/venv/django-env/bin/activate

vscode:
  extensions:
    - "ms-python.python"
