# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: 'Terminal 1'
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: 'Terminal 2'
    command: source /workspace/venv/bin/activate

vscode:
  extensions:
    - "ms-python.python@v2022.14.0"
