# Generated by Django 4.1.1 on 2022-09-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_account_customer_created_ledger_account_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='created',
            new_name='created_at',
        ),
    ]
