# Generated by Django 4.1.1 on 2022-10-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_rename_created_account_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='employee',
        ),
    ]
