# Generated by Django 4.1.1 on 2022-10-11 21:17

import bank_app.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_alter_account_account_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_uuid',
        ),
        migrations.AddField(
            model_name='account',
            name='ban',
            field=models.CharField(default=bank_app.util.gen_ban, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='iban',
            field=models.CharField(default=bank_app.util.gen_iban, max_length=34),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.account', to_field='ban'),
        ),
    ]
