# Generated by Django 4.1.1 on 2022-10-11 21:23

import bank_app.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_remove_account_account_uuid_account_ban_account_iban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='ban',
            field=models.CharField(default=bank_app.util.gen_ban, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.account'),
        ),
    ]
