# Generated by Django 4.1.1 on 2022-10-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_remove_account_id_alter_account_ban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='direct_transaction_with_bank',
            field=models.BooleanField(default=False),
        ),
    ]
