# Generated by Django 4.1.1 on 2022-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_ledger_direct_transaction_with_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='secret_for_2fa',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
