# Generated by Django 4.1.1 on 2022-12-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_ledger_direct_transaction_with_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTransfer',
            fields=[
                ('idempotency_key', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RESERVED', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
