# Generated by Django 4.1.1 on 2022-12-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_externaltransfer_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.account'),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='to_account',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='to_bank',
            field=models.CharField(max_length=5),
        ),
    ]
