# Generated by Django 4.1.1 on 2022-12-20 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0013_alter_externaltransfer_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externaltransfer',
            old_name='to_account',
            new_name='credit_account',
        ),
        migrations.RenameField(
            model_name='externaltransfer',
            old_name='from_account',
            new_name='debit_account',
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.UUID('ace72136-5333-400f-a818-0838f1630607'), primary_key=True, serialize=False, unique=True),
        ),
    ]
