# Generated by Django 4.1.1 on 2022-12-20 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_rename_to_account_externaltransfer_credit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransfer',
            name='from_bank',
            field=models.CharField(default='8000', max_length=5),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.UUID('cb6d6e91-728a-461e-a309-e1dbedaee7ab'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='debit_account',
            field=models.CharField(max_length=10),
        ),
    ]
