# Generated by Django 4.1.1 on 2022-12-15 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_alter_customer_secret_for_2fa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('pay_once_per_n_days', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Minimum value is 1'), django.core.validators.MaxValueValidator(356, message='Maximum value is 365')])),
                ('time_to_live', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(356)])),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_account_for_recurring_payment', to='bank_app.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.customer')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_account_for_recurring_payment', to='bank_app.account')),
            ],
        ),
    ]
