# Generated by Django 4.1.1 on 2023-01-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0015_externaltransfer_from_bank_and_more'),
        ('bank_app', '0015_recurring_payment'),
    ]

    operations = [
    ]
