# Generated by Django 4.1.1 on 2022-12-20 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0015_externaltransfer_from_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransfer',
            name='debit_account',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.UUID('5e960a90-706c-4b0c-9869-d3fa9ce9e586'), primary_key=True, serialize=False, unique=True),
        ),
    ]
