# Generated by Django 4.1.1 on 2023-01-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0016_merge_20230107_2134'),
        ('bank_app', '0016_notification'),
    ]

    operations = [
    ]
