# Generated by Django 4.1.1 on 2023-01-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0018_rename_stock_id_stock_stock_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_symbol',
            field=models.CharField(choices=[('NOVOb', 'Novob'), ('GN', 'Gn'), ('DANSKE', 'Danske'), ('GMAB', 'Gmab'), ('DSV', 'Dsv')], max_length=8),
        ),
        migrations.AlterField(
            model_name='stocks_ledger',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.stock'),
        ),
    ]
