# Generated by Django 4.1.1 on 2023-01-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0019_alter_stock_stock_symbol_alter_stocks_ledger_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('belongs_to', 'stock_symbol')},
        ),
    ]
