# Generated by Django 4.1.1 on 2023-01-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0020_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.account'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_symbol',
            field=models.CharField(choices=[('GN.CO', 'Gn'), ('DANSKE.CO', 'Danske'), ('ORSTED.CO', 'Orsted'), ('PNDORA.CO', 'Pndora'), ('JYSK.CO', 'Jysk')], max_length=15),
        ),
    ]
