# Generated by Django 4.1.1 on 2023-01-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0021_alter_customer_phone_alter_ledger_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.account'),
        ),
    ]
