# Generated by Django 4.1.1 on 2023-01-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0020_alter_notification_id'),
        ('bank_app', '0022_alter_ledger_account'),
    ]

    operations = [
    ]
