# Generated by Django 4.1.1 on 2023-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0023_merge_20230115_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransfer',
            name='from_bank',
            field=models.CharField(default='8001', max_length=5),
        ),
    ]
