# Generated by Django 4.1.1 on 2023-01-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0024_alter_externaltransfer_from_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransfer',
            name='from_bank',
            field=models.CharField(default='8000', max_length=5),
        ),
    ]
