version: "3.8"

services:

    db:
        image: postgres:13-alpine
        ports:
            - 5432:5432
        # volumes:
        #     - db_data:/var/lib/postgresql/data/
        env_file:
            - db_${RTE}.env

    app:
        build: .
        ports:
            - 8000:8000
            - 8080:8080
        env_file:
            - db_${RTE}.env
        volumes:
            - .:/app/
            - static:/static/
            - media:/media/
        depends_on:
            - db

    # nginx:
    #     build: nginx/
    #     ports:
    #         - 443:443
    #         - 80:80
    #     volumes:
    #         - ./nginx/${RTE}/conf.d/:/etc/nginx/conf.d/
    #         - ./certs/:/etc/letsencrypt/
    #         - static:/static/
    #         - media:/media/
    #     depends_on:
    #         - app

volumes:
    db_data:
    static:
    media: